# Generated by Django 4.2.7 on 2024-02-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=25, null=True)),
                ('link_resposta', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionário',
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Resposta Curta', 'Resposta Curta'), ('Resposta Longa', 'Resposta Longa'), ('Única Escolha', 'Única Escolha'), ('Várias Escolhas', 'Várias Escolhas'), ('Dropdown', 'Dropdown')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(null=True, verbose_name='Nome')),
                ('area', models.BooleanField(default=False)),
                ('local', models.BooleanField(default=False)),
                ('questionario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.questionario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.tipo')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True, verbose_name='Título')),
                ('descricao', models.TextField(max_length=255, null=True)),
                ('datahora', models.DateTimeField(auto_now_add=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.area')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.local')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.status')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
