# Generated by Django 5.0.2 on 2024-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "Área", "verbose_name_plural": "Áreas"},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedbacks"},
        ),
        migrations.AlterModelOptions(
            name="questionario",
            options={
                "verbose_name": "Questionário",
                "verbose_name_plural": "Questionário",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Status", "verbose_name_plural": "Status"},
        ),
        migrations.AlterModelOptions(
            name="tipo",
            options={"verbose_name": "Tipo", "verbose_name_plural": "Tipos"},
        ),
        migrations.AlterField(
            model_name="questao",
            name="area",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tipo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Resposta Curta", "Resposta Curta"),
                    ("Resposta Longa", "Resposta Longa"),
                    ("Única Escolha", "Única Escolha"),
                    ("Várias Escolhas", "Várias Escolhas"),
                    ("Dropdown", "Dropdown"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
