# Generated by Django 4.2.7 on 2024-02-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField(null=True, verbose_name="Comentário")),
                ("datahora", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "feedback_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
            },
        ),
    ]
