# Generated by Django 4.2.7 on 2024-03-01 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="usuario",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
