# Generated by Django 4.2.7 on 2024-03-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_usuario_options_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='imagem',
            field=models.ImageField(null=True, upload_to='feedback/static/img/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datahora',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='descricao',
            field=models.TextField(max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.local', verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(choices=[('Resposta Curta', 'Resposta Curta'), ('Resposta Longa', 'Resposta Longa'), ('Única Escolha', 'Única Escolha'), ('Várias Escolhas', 'Várias Escolhas'), ('Dropdown', 'Dropdown'), ('Imagem', 'Imagem')], max_length=50, unique=True),
        ),
    ]
