# Generated by Django 4.2.7 on 2024-03-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_imagem_alter_feedback_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/static/img/', verbose_name='Imagem'),
        ),
    ]
