# Generated by Django 5.0.3 on 2024-03-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/static/coment/img', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
    ]
